from fastapi import APIRouter, HTTPException, status
from fastapi.responses import FileResponse
from app.models.response_models import JobStatusResponse
from app.services.queue_service import queue_service
from app.services.storage_service import storage_service
from app.core.logger import logger

router = APIRouter(prefix="/api")

@router.get(
    "/status/{job_id}",
    response_model=JobStatusResponse,
    summary="Get job execution status",
    description="Returns the progress percentage, active step description, and list of output file names for a job."
)
async def get_job_status(job_id: str) -> JobStatusResponse:
    try:
        status_info = queue_service.get_job_status(job_id)
        return status_info
    except Exception as e:
        logger.error(f"Error fetching job status for {job_id}: {e}")
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Failed to fetch status for job {job_id}: {str(e)}"
        )

@router.get(
    "/download/{job_id}/{filename}",
    response_class=FileResponse,
    summary="Download processed output asset file",
    description="Downloads a specific file (e.g. BMP, TIFF, SVG, PNG) generated by the processing pipeline."
)
async def download_file(job_id: str, filename: str) -> FileResponse:
    try:
        # Resolve file path (downloads from S3 if needed)
        local_path = storage_service.get_local_path(job_id, filename)
        
        if not local_path.exists():
            raise HTTPException(
                status_code=status.HTTP_404_NOT_FOUND,
                detail=f"File {filename} not found for job {job_id}"
            )
            
        # Determine media type / headers
        media_type = "application/octet-stream"
        ext = local_path.suffix.lower()
        if ext == ".png":
            media_type = "image/png"
        elif ext == ".bmp":
            media_type = "image/bmp"
        elif ext == ".tif" or ext == ".tiff":
            media_type = "image/tiff"
        elif ext == ".svg":
            media_type = "image/svg+xml"
        
        logger.info(f"Downloading file {filename} for job {job_id}")
        return FileResponse(
            path=str(local_path),
            media_type=media_type,
            filename=filename
        )
    except FileNotFoundError as e:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=str(e)
        )
    except Exception as e:
        logger.error(f"Error processing download for {filename} (job: {job_id}): {e}")
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Download failed: {str(e)}"
        )
