from app.core.database import Base

def get_model(model_name: str):
    """
    Get a SQLAlchemy model class by its table name (or class name generated by automap).
    Requires init_db() to have been called on startup.
    
    Example:
        ProjectAsset = get_model('project_asset')
    """
    if not Base.classes:
        raise RuntimeError("Database schema has not been reflected yet. Ensure init_db() is called.")
    
    if model_name in Base.classes:
        return Base.classes[model_name]
    
    # Try capitalizing or finding exact match
    for name, cls in Base.classes.items():
        if name.lower() == model_name.lower():
            return cls
            
    raise ValueError(f"Model/Table '{model_name}' not found in reflected database schema.")
